### ISSUE TITLE
在gh-pages DIY的时候，选主教职业之后页面会变空白

### ISSUE THREAD

**Issue by ghost** [Haoxuan8/sve-card#3]
![屏幕截图(11)](https://github.com/Haoxuan8/sve-card/assets/112806927/563ba389-057b-4571-a498-aee0aadc0d96)
![屏幕截图(12)](https://github.com/Haoxuan8/sve-card/assets/112806927/58a428c0-9f4d-4e2d-a395-668d42a5fc92)
我试用了所有VPN线路，无论是手机端的chrome还是PC的edge浏览器都会触发这个问题
无论是什么类型的卡和模板，一选主教职业之后页面会变为图一这样的空白

**Comment by ghost** [comment]
另外问一下。中文版的字体、进场离场之类的图标。其他稀有度的卡片模板最近有计划更新吗？

**Comment by Haoxuan8** [comment]
已修复，中文版或者英文版的模板后续考虑增加。
